export const MAIN_ADD_FOLDER = 'MAIN/ADD_FOLDER'
export const MAIN_ITEM_RENAME = 'MAIN/MAIN_ITEM_RENAME'
export const MAIN_SET_SELECTED = 'MAIN_SET_SELECTED'
export const MAIN_REMOVE_SELECTED = 'MAIN_REMOVE_SELECTED'


export const STORAGE_GET = 'STORAGE/GET'
export const STORAGE_GET_FIELDS = 'STORAGE/GET_FIELDS'
export const STORAGE_GET_LIST = 'STORAGE/GET_LIST'
export const STORAGE_GET_CHILDREN = 'STORAGE/GET_CHILDREN'


export const FOLDER_GET = 'FOLDER/GET'
export const FOLDER_GET_FIELDS = 'FOLDER/GET_FIELDS'
export const FOLDER_GET_CHILDREN = 'FOLDER/GET_CHILDREN'


export const FILE_GET_LINK = 'FILE/GET_LINK'
export const FILE_ADD_TO_CURRENT = 'FILE/RENAME'


export const APP_SETTINGS_GET = 'APP_SETTINGS/GET'
export const APP_SETTINGS_SET = 'APP_SETTINGS/SET'

export const USER_SETTINGS_GET = 'USER_SETTINGS/GET'
export const USER_SETTINGS_SET = 'USER_SETTINGS/SET'


export const MOUSE_DOWN = 'MOUSE/DOWN'
export const MOUSE_UP = 'MOUSE/UP'
